### ISSUE TITLE
Actividad 2: Diseño colocación del sistema de sensores ultrasónicos. 

### ISSUE THREAD

**Issue by AndresFloresF** [mrg-mex/Proyecto_02_semestre_2023-1#2]
Actividades propuestas para resolver la problemática:

1. Buscar CAD de sensor ultrasónico para dimensionar con respecto al robot móvil.
![IdeaUltrasonicos](https://user-images.githubusercontent.com/42392795/205776081-677d17e8-28a5-4adc-8327-7886d8404619.png)
2. Observar que se requiere para poder colocar tres sensores ultrasónicos integrado al chasis o en un extra al chasis. 

3. Primer diseño de base para ultrasónicos, dentro de chasis o en pieza extra.

**Comment by AndresFloresF** [comment]
Actividad 1 Resuelta, ya se cuenta con el archivo CAD 
![UltrasonicoCAD](https://user-images.githubusercontent.com/42392795/205777250-e42cf220-d11c-4d62-b258-6cb91af818cb.png)
Archivo:  hc sr04 ultrasonic sensor.SLDPRT

**Comment by AndresFloresF** [comment]
Actividad 2 a medias, revisar resto de consideraciones:

Altura chasis robot en la parte inferior: 25 mm
Altura sensor ultrasónico colocado horizontalmente: 21 mm
![UltrasonicoEnsamble](https://user-images.githubusercontent.com/42392795/205777464-aa68976c-feba-4611-80f7-d79fc7b3a224.png)

**Comment by AndresFloresF** [comment]
Primer propuesta, 
![PrimerPropuesta](https://user-images.githubusercontent.com/42392795/208817526-853c5705-b23c-470b-a134-d0af54fa655f.jpg)
![IntentoEnsamble](https://user-images.githubusercontent.com/42392795/208817527-3c2f391e-ccfd-42c2-a81f-4137159f498b.jpg)
ultrasónicos, verificando si es posible colocar en ensamble y como

**Comment by SebassBv** [comment]
Se propuso una nueva distribución de los sensores ultrasónicos. Se añadieron ganchos a la estructura del sensor forntal y se modificó el chasis para la colocación de los sensores laterales

![Imagen de WhatsApp 2022-12-22 a las 00 45 41](https://user-images.githubusercontent.com/42391642/209074337-026f9dad-bf7f-4116-bca6-3dfafd0bd94a.jpg)

![Imagen de WhatsApp 2022-12-22 a las 00 44 57](https://user-images.githubusercontent.com/42391642/209074370-45ab128c-e5f9-4baa-a523-8d0926db7aa5.jpg)

**Comment by AndresFloresF** [comment]
Chasis y distribución en espera de aprobación por parte del maestro, se puede imprimir el diseño actual de chasis v2 acorde al equipo de trabajo @ErikFiUNAM 
![WhatsApp Image 2022-12-22 at 00 43 43](https://user-images.githubusercontent.com/42392795/209074697-44fe0d36-664f-4644-bf8f-7667b1cf1117.jpg)

**Comment by ErikFiUNAM** [comment]
Deje imprimiendo el Chasis para hacer pruebas con el ensamble, la siguiente
semana regresó para ver como quedó. Cualquier cosa les aviso.

Atte. M.I. Erik Peña Medina.
