### ISSUE TITLE
Actividad 3: Cambio diseño superior de robot móvil, NUEVO Ventilador para Raspberry 

### ISSUE THREAD

**Issue by AndresFloresF** [mrg-mex/Proyecto_02_semestre_2023-1#3]
Actividades propuestas para resolver la problemática:
1.  Buscar o realizar modelo CAD de ventilador mini para Raspberry. 
(Posiblemente tomar medidas del ventilador, buscar o diseñar, para tenerlo en CAD) 
2. Revisar y eliminar consideraciones actuales del ventilador en la parte superior (ya señaladas en la imagen)
![CambiosVentilador](https://user-images.githubusercontent.com/42392795/205772753-8667412a-7d14-42dd-b7dd-17b378644642.png)
3. Colocar en ensamble  en su posición, considerando como se colocará, y que permita conocer la altura para el diseño de la actividad 5.  [https://github.com/mrg-mex/Proyecto_02_semestre_2023-1/issues/5](url)

**Comment by GarciaMejiaLuis** [comment]
Para el modelo CAD del ventilador dual mini para raspberry se uso el modelo CAD de otro ventilador similar, se ajusto sus medidas a la del ventilador RaspBerry.
![image](https://user-images.githubusercontent.com/47509456/208992839-22434585-e8b3-497c-a0ca-b8723b1b79d6.png)

Al duplicarlo y ponerles restricciones de ensamble se obtuvo lo siguiente.  

![image](https://user-images.githubusercontent.com/47509456/208993137-c59d086a-3942-4b1d-9816-c63bd806df79.png)

Ventilador Original

![image](https://user-images.githubusercontent.com/47509456/208993205-f829833b-9918-48b0-ba4c-68a59c77ad45.png)

**Comment by GarciaMejiaLuis** [comment]
Se acomodo el ventilador en el CAD y se coloco restricciones de posición en el mismo para fijarlo en una ubicación.
![image](https://user-images.githubusercontent.com/47509456/209248982-5d268f80-3744-450d-b2f7-da5f052c25b6.png)

Por otro lado se modifico la antigua base del ventilador para que ocupe el menor espacio posible.
![image](https://user-images.githubusercontent.com/47509456/209248993-2a58ca6c-2d61-4886-850d-8fc9ca15408a.png)

El resultado final fue el siguiente
![image](https://user-images.githubusercontent.com/47509456/209249033-f16cf32f-cf45-41f6-a96e-6671e9cfe023.png)
