### ISSUE TITLE
Actividad 4: Modificaciones en chasis para problemáticas actuales. 

### ISSUE THREAD

**Issue by AndresFloresF** [mrg-mex/Proyecto_02_semestre_2023-1#4]
Actividades a realizar en esta parte :

PARTE SUPERIOR:
Editar chasis para liberar la entrada MicroSD de la raspberry 
![image](https://user-images.githubusercontent.com/42392795/205777682-520dea9e-80e2-411b-af43-e19d7da930a1.png)

Arreglar orificios para postes de latón que sujeten la raspberry.
![image](https://user-images.githubusercontent.com/42392795/205777771-4161f8c6-2a6e-44b3-b295-aa6a5326d7bc.png)

PARTE INFERIOR:
- Colocación de posible PCB para los puente H en la parte inferior del robot, antes de sujetadores de encoder.
![image](https://user-images.githubusercontent.com/42392795/205777907-3288dcb6-5299-4458-8570-502a9dce2123.png)
- Dar una solución para pasar cables de la parte superior a la inferior y conectar los componentes actuales (ultrasónicos, puente H, motores a donde correspondan)

**Comment by SebassBv** [comment]
PARTE SUPERIOR

Se modificó el diámetro del agujero para los postes de latón. Se probarán 3 medidas: 2.6 mm, 2.7 mmm y 2.65 mm para ver cual diámetro es el más justo para los postes. 

![modif_diametro_postes](https://user-images.githubusercontent.com/42391642/207518100-105b1191-a907-441d-89de-605d2ebef5e8.jpg)

![image](https://user-images.githubusercontent.com/42391642/207518226-ea23a4e5-086f-4659-bfa9-cfa024aa4e32.png)

**Comment by SebassBv** [comment]
PARTE SUPERIOR

Se modificó el chasis, principalmente el croquis que contiene las extrusiones de los orificios para liberar el puerto de entrada microSD, la estructura se desplazó más lejos de la baseCam y se extruyeron ligeramente los soportes para lograr dicha liberación

![image](https://user-images.githubusercontent.com/42391642/207518534-98d92d67-558f-445a-92e9-60ccf64c2741.png)

![image](https://user-images.githubusercontent.com/42391642/207518604-aa88fc3e-26a1-4ffe-94c4-740cb53e23b5.png)

**Comment by SebassBv** [comment]
PARTE INFERIOR

Se agregó un nuevo componente llamado "agarradera" para lograr la contención y guía de los cables que conectarán la Rasperry y el doble puente H, además se agregó una ranura para que puedan pasar con mayor facilidad las conexiones sin afectar el funcionamiento del robot.

![image](https://user-images.githubusercontent.com/42391642/207795867-3850a140-18e5-45a3-8adb-77d37afa85bb.png)

**Comment by SebassBv** [comment]
PARTE INFERIOR

Se añadió el soporte que contendrá el puente H por debajo del Raspbot.

![image](https://user-images.githubusercontent.com/42391642/207820046-35979eaa-355e-4a72-8cd2-0e71bd6f66ab.png)

![image](https://user-images.githubusercontent.com/42391642/207820390-1ace32fe-ee30-4311-8242-bea7091a934c.png)

![image](https://user-images.githubusercontent.com/42391642/207820538-0e3c444f-44ca-4379-971d-35b73ecbe03c.png)

**Comment by AndresFloresF** [comment]
Chasis en espera de sistema para colocar ultrasónicos, cambios agregados a rama principal

**Comment by SebassBv** [comment]
Ranuración del chasis para la colocación del sensor ultrasónico frontal y moficiación de éste en la parte superior para colocación de los laterales

![Imagen de WhatsApp 2022-12-22 a las 00 44 57](https://user-images.githubusercontent.com/42391642/209074560-276c9e94-9427-4229-a74e-9d8ed5535a6b.jpg)

![Imagen de WhatsApp 2022-12-22 a las 00 44 37](https://user-images.githubusercontent.com/42391642/209074596-4cd1d2c1-ccad-4e15-80f4-e5c0d34bd6b5.jpg)

**Comment by AndresFloresF** [comment]
Se considera que no existan mas cambios en chasis, por el momento se concluye la actividad 4.
