### ISSUE TITLE
Actividad 5: Detalles para base superior código QR. 

### ISSUE THREAD

**Issue by AndresFloresF** [mrg-mex/Proyecto_02_semestre_2023-1#5]
Actividades propuestas para resolver la problemática:

1. Plantear en base a las modificaciones realizadas en chasis y ventilador, la altura y sistema de colocación para el código QR.
(Venir al laboratorio y observar ejemplos).
![BaseSuperiorQR](https://user-images.githubusercontent.com/42392795/205771340-ca10a548-144f-4a2f-8bc4-f58b0b3c35a3.png)

Problemática encontrada: Se deben completar las modificaciones anteriores para intentar dar una solución por las variaciones que darán:
- Actividad 3 [https://github.com/mrg-mex/Proyecto_02_semestre_2023-1/issues/4](url)
- Actividad 4 [https://github.com/mrg-mex/Proyecto_02_semestre_2023-1/issues/4](url)

**Comment by GarciaMejiaLuis** [comment]
Acomodo de la base del código QR y corrección del formato del ventilador

-Nuevo ensamble y acomodo del ventilador y base del código QR.

-Se uso un nuevo documento para el ventilador, debido que la anterior versión estaba en formato ensamble y no como formato pieza.

-Se cambio una restricción de coincidencia de la base del código QR debido a que provocaba problemas para poder ensamblar de manera correcta la pieza con los separadores M2_5

-Se retiro la antigua base del ventilador
![imagen](https://user-images.githubusercontent.com/47509456/210687570-81eb41c0-f60b-40d8-9d5d-fa93f8b5811e.png)

![imagen](https://user-images.githubusercontent.com/47509456/210687809-8937be83-fba1-40d7-8b7c-c0429040c72b.png)

**Comment by GarciaMejiaLuis** [comment]
Archivos Actualizados #13

**Comment by AndresFloresF** [comment]
Modificaciones en CAD concluidas, en espera de resultados de impresion 3D.
