### ISSUE TITLE
Actividad 6: Recuperar diseño actual de pieza. Rueda bola loca.  

### ISSUE THREAD

**Issue by AndresFloresF** [mrg-mex/Proyecto_02_semestre_2023-1#6]
Actividades propuestas para resolver la problemática:

1. Medir y obtener pieza impresa del sistema rueda bola loca del robot.
2. Observar diferencias entre CAD y medidas de pieza física.
3. Realizar modificaciones en la pieza correspondiente.

**Comment by GarciaMejiaLuis** [comment]
Actividad 1. Medir y obtener las medidas de la pieza impresa del sistema de rodamiento del robot


![imagen](https://user-images.githubusercontent.com/47509456/205769981-72d8c06c-8c67-4537-b4bd-b2872d05764d.png)


![imagen](https://user-images.githubusercontent.com/47509456/205770048-87d205a0-121e-43d5-be27-6c2d488c36c5.png)

**Comment by AndresFloresF** [comment]
**DIFERENCIAS DETECTADAS ENTRE CAD Y PIEZA REAL CON MODIFICACIONES A REALIZAR.** 
- Cambio de altura de 30mm a 26.5 mm , para tener mayor aproximación al valor medido (28.83 mm)
- Reducción de radio inferior de 15.25 mm a 13 mm , para corresponder al diámetro medido de 26 mm 
- Cambio de espesor de 3 mm a 2.5 mm por la medida real de 2.4 mm, considerando 1mm de tolerancia para impresión. 
- Radio Superior, cambio de ubicación de cota a vértice previo al arco, valor de 9.85, modificado a para obtener un radio similar al obtenido de 12.4 mm , nuevo valor de 12.5 mm con interior de 10 mm mas 2.5 mm de borde, 12.5 mm .
![image](https://user-images.githubusercontent.com/42392795/209191154-08b581b0-55b1-4ffa-86eb-6b05d03ddd71.png)
![image](https://user-images.githubusercontent.com/42392795/209194052-5a047cf1-066d-4531-b459-ec1d20ef0add.png)

- Cambio de diámetro interior pieza de 2.5 mm a 2.3 mm , cercano al 2.2 mm de medida real. 
- Sin modificaciones en distancia de circulo interior de pieza por dificultad de obtener la medida.
Aumento de espesor de extrusión a piezas de 2mm a 2.6 mm, cercano al 2.54 mm de medida real. 
![image](https://user-images.githubusercontent.com/42392795/209195648-490bc5e1-2334-46c4-be06-12a9dcdfc788.png)
- Rediseño de soportes triangulares para piezas con 15.5 mm de altura.
![image](https://user-images.githubusercontent.com/42392795/209196619-4cdae76a-0e40-44dd-ba69-243093a5c5b1.png)

**Comment by AndresFloresF** [comment]
Se decidió retornar algunos cambios como lo fue la altura y el radio interior y exterior de la pieza, al tener complicaciones en el ensamble  y se podía observar que requería mas altura en comparación de las llantas. 
![image](https://user-images.githubusercontent.com/42392795/209210435-0d59d2d4-8fcc-4ad3-a275-84dcf7e34b0e.png)

Ahora bien, se realizo pequeñas modificaciones en la ubicación de orificios del chasis, menor a 2 mm de cada modificación.
![image](https://user-images.githubusercontent.com/42392795/209210610-dff0f174-c85f-4ee1-9585-51da196a6469.png)
